name: Build with Gradle
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
      - name: Generate HTML test report
        run: ./gradlew jacocoTestReport
      - name: Archive HTML test report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: test/reports/
      - name: Create deployment status
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          environment-url: https://github.com/FerJoanEne/core-fitech/runs/${{ env.GITHUB_RUN_ID }}/artifacts/download?path=test/reports/index.html
          log-url: https://github.com/FerJoanEne/core-fitech/actions/runs/${{ env.GITHUB_RUN_ID }}
          description: Test report is ready
          auto-inactive: true
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64
          JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.18-10/x64
